from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List

import streamlit as st

from core.llm_client import LlmClient, load_config
from core.risk_engine import build_risk_item, calculate_risk_score, compute_risk_level
from core.state_manager import find_requirement, find_risk_by_req_id, generate_risk_id, get_state, save_state
from utils.change_tracker import log_change
from utils.ui import apply_reference_theme, render_hero, render_workflow_sidebar


def render_risk_matrix(risk_items: List[Dict[str, Any]]) -> str:
    matrix = {(impact, likelihood): [] for impact in range(1, 6) for likelihood in range(1, 6)}
    for item in risk_items:
        key = (int(item.get("impact", 1)), int(item.get("likelihood", 1)))
        matrix[key].append(item.get("req_id", ""))

    html = ['<table style="border-collapse:collapse;width:100%;font-size:13px;">']
    html.append("<tr><th style='padding:6px;border:1px solid #ddd;'>Impact \\ Likelihood</th>")
    for likelihood in range(1, 6):
        html.append(f"<th style='padding:6px;border:1px solid #ddd;'>{likelihood}</th>")
    html.append("</tr>")

    for impact in range(5, 0, -1):
        html.append(f"<tr><th style='padding:6px;border:1px solid #ddd;'>{impact}</th>")
        for likelihood in range(1, 6):
            score = impact * likelihood
            if score >= 12:
                bg = "#FECACA"
            elif score >= 6:
                bg = "#FEF3C7"
            else:
                bg = "#DCFCE7"
            reqs = "<br/>".join(matrix[(impact, likelihood)]) or "&nbsp;"
            html.append(
                f"<td style='vertical-align:top;padding:6px;border:1px solid #ddd;background:{bg};min-width:80px;'>{reqs}</td>"
            )
        html.append("</tr>")
    html.append("</table>")
    return "".join(html)


def generate_or_update_risk(ps: Dict[str, Any], requirement: Dict[str, Any], parsed_req: Dict[str, Any], use_llm: bool, llm_client: LlmClient) -> str:
    existing = find_risk_by_req_id(ps, requirement["req_id"])
    record = build_risk_item(
        requirement,
        parsed_req,
        risk_id=existing["risk_id"] if existing else generate_risk_id(ps),
        use_llm=use_llm,
        llm_client=llm_client,
        review_status="Draft",
        last_edited_by="llm",
    )
    if existing:
        old_record = deepcopy(existing)
        existing.update(record)
        log_change(ps, "risk", existing["risk_id"], "Regenerated", "record", old_record, existing, "llm", "Regenerated by risk page")
        return existing["risk_id"]

    ps["risk_items"].append(record)
    log_change(ps, "risk", record["risk_id"], "Created", "record", None, record, "llm", "Initial risk generation")
    return record["risk_id"]


apply_reference_theme()

ps = get_state()
use_llm = bool(st.session_state.get("use_llm", False))
llm_client = LlmClient(load_config())

with st.sidebar:
    render_workflow_sidebar("Risk Assessment")

render_hero(
    "Risk-Based Prioritization",
    "Risk Assessment",
    "Score the approved structured requirements, review rationale, and lock down the priorities that deserve the most test depth.",
)

parsed_requirements = [item for item in ps["parsed_requirements"] if item.get("review_status") == "Approved"]
risk_items = ps["risk_items"]

high_count = len([item for item in risk_items if item.get("risk_level") == "High"])
medium_count = len([item for item in risk_items if item.get("risk_level") == "Medium"])
low_count = len([item for item in risk_items if item.get("risk_level") == "Low"])

sum1, sum2, sum3 = st.columns(3)
with sum1:
    st.metric("高风险", high_count)
with sum2:
    st.metric("中风险", medium_count)
with sum3:
    st.metric("低风险", low_count)

st.subheader("风险矩阵热力图")
st.markdown(render_risk_matrix(risk_items), unsafe_allow_html=True)

if st.button("批量生成所有风险项", type="secondary"):
    st.session_state["confirm_batch_risk"] = True

if st.session_state.get("confirm_batch_risk"):
    st.info("将对所有 `Approved` 的结构化需求生成风险项，并跳过已 Confirmed 的风险记录。再次点击确认。")
    if st.button("确认批量生成风险项", key="confirm_batch_risk_btn", type="secondary"):
        generated = 0
        skipped = 0
        for parsed_req in parsed_requirements:
            requirement = find_requirement(ps, parsed_req["req_id"])
            existing = find_risk_by_req_id(ps, parsed_req["req_id"])
            if existing and existing.get("review_status") == "Confirmed":
                skipped += 1
                continue
            generate_or_update_risk(ps, requirement, parsed_req, use_llm, llm_client)
            generated += 1
        save_state(ps)
        st.session_state["confirm_batch_risk"] = False
        st.success(f"已生成/更新 {generated} 条风险项，跳过 {skipped} 条")
        st.rerun()

ranked_requirements = []
for parsed_req in parsed_requirements:
    requirement = find_requirement(ps, parsed_req["req_id"])
    risk = find_risk_by_req_id(ps, parsed_req["req_id"])
    score = risk.get("risk_score", 0) if risk else 0
    level = risk.get("risk_level", "Draft") if risk else "Draft"
    ranked_requirements.append((score, f"{requirement['req_id']} - {requirement['title']} [{level} / {score}分]", requirement["req_id"]))
ranked_requirements.sort(key=lambda item: item[0], reverse=True)

if not ranked_requirements:
    st.info("还没有可评估的需求。先去 Structured Requirement Review 页面批准至少一条结构化需求。")
    st.stop()

labels = [item[1] for item in ranked_requirements]
label_to_req_id = {item[1]: item[2] for item in ranked_requirements}
selected_label = st.selectbox("需求列表（按风险分降序）", labels)
selected_req_id = label_to_req_id[selected_label]

selected_requirement = find_requirement(ps, selected_req_id)
selected_parsed = next(item for item in parsed_requirements if item["req_id"] == selected_req_id)
selected_risk = find_risk_by_req_id(ps, selected_req_id)

if st.button("生成当前需求的风险评估"):
    generate_or_update_risk(ps, selected_requirement, selected_parsed, use_llm, llm_client)
    save_state(ps)
    st.success("风险评估已生成")
    st.rerun()

if selected_risk is None:
    st.info("当前需求还没有风险评估。")
    st.stop()

is_locked = selected_risk.get("review_status") == "Confirmed"
if is_locked:
    st.warning("⚠️ 此风险评估已确认，字段只读。如需修改，请先降级为 Draft。")

st.subheader("风险详情编辑器")
st.text_area("需求原文（只读）", value=selected_requirement["raw_text"], height=120, disabled=True)
title = st.text_input("风险标题", value=selected_risk.get("risk_title", ""), disabled=is_locked)
summary = st.text_area("风险摘要", value=selected_risk.get("risk_summary", ""), height=100, disabled=is_locked)

impact = st.slider(
    "影响程度 Impact",
    1,
    5,
    value=int(selected_risk.get("impact", 2)),
    help="出错后对用户或系统的影响有多严重",
    disabled=is_locked,
)
likelihood = st.slider(
    "出错可能 Likelihood",
    1,
    5,
    value=int(selected_risk.get("likelihood", 2)),
    help="这个功能出现 bug 的可能性有多大",
    disabled=is_locked,
)
complexity = st.slider(
    "实现复杂度 Complexity",
    1,
    5,
    value=int(selected_risk.get("complexity", 2)),
    help="实现和测试这个功能的难度",
    disabled=is_locked,
)
usage_freq = st.slider(
    "使用频率 Usage Frequency",
    1,
    5,
    value=int(selected_risk.get("usage_frequency", 2)),
    help="用户使用这个功能的频率",
    disabled=is_locked,
)

risk_score = calculate_risk_score(impact, likelihood, complexity, usage_freq)
risk_level = compute_risk_level(risk_score)
level_icon = {"High": "🔴", "Medium": "🟡", "Low": "🟢"}[risk_level]
st.metric("风险总分", f"{risk_score}", f"{level_icon} {risk_level}")

with st.expander("LLM / 规则引擎评分理由", expanded=True):
    st.write(selected_risk.get("rationale", ""))

if selected_risk.get("evidence_keywords"):
    st.write("触发关键词：", "  ".join(f"`{item}`" for item in selected_risk["evidence_keywords"]))

mitigation_hint = st.text_area("缓解建议", value=selected_risk.get("mitigation_hint", ""), height=100, disabled=is_locked)
change_reason = st.text_input("修改原因（保存时必填）", key=f"risk_reason_{selected_risk['risk_id']}")

if is_locked:
    if st.button("降级为 Draft 并编辑"):
        if not change_reason.strip():
            st.error("请先填写修改原因")
        else:
            old_record = deepcopy(selected_risk)
            selected_risk["review_status"] = "Draft"
            selected_risk["last_edited_by"] = "human"
            log_change(ps, "risk", selected_risk["risk_id"], "Modified", "review_status", old_record["review_status"], "Draft", "human", change_reason)
            save_state(ps)
            st.success("已降级为 Draft，现在可以编辑")
            st.rerun()

btn1, btn2, btn3 = st.columns(3)
save_clicked = btn1.button("Save", type="primary", disabled=is_locked)
confirm_clicked = btn2.button("Confirm", disabled=is_locked)
reject_clicked = btn3.button("Reject", disabled=is_locked)

regen_label = "强制重新生成（会覆盖确认结果）" if is_locked else "重新生成"
if st.button(regen_label, type="secondary"):
    if is_locked:
        st.session_state["confirm_force_regen_risk"] = True
    else:
        generate_or_update_risk(ps, selected_requirement, selected_parsed, use_llm, llm_client)
        save_state(ps)
        st.success("风险评估已重新生成")
        st.rerun()

if st.session_state.get("confirm_force_regen_risk"):
    st.warning("再次点击确认会覆盖当前 Confirmed 风险评估。")
    if st.button("确认强制重新生成风险评估", key="force_regen_risk"):
        generate_or_update_risk(ps, selected_requirement, selected_parsed, use_llm, llm_client)
        save_state(ps)
        st.session_state["confirm_force_regen_risk"] = False
        st.success("已强制覆盖风险评估")
        st.rerun()

if save_clicked or confirm_clicked or reject_clicked:
    if not change_reason.strip():
        st.error("请填写修改原因后再保存")
    else:
        old_record = deepcopy(selected_risk)
        selected_risk["risk_title"] = title.strip()
        selected_risk["risk_summary"] = summary.strip()
        selected_risk["impact"] = impact
        selected_risk["likelihood"] = likelihood
        selected_risk["complexity"] = complexity
        selected_risk["usage_frequency"] = usage_freq
        selected_risk["risk_score"] = risk_score
        selected_risk["risk_level"] = risk_level
        selected_risk["mitigation_hint"] = mitigation_hint.strip()
        selected_risk["last_edited_by"] = "human"

        action = "Edited"
        if confirm_clicked:
            selected_risk["review_status"] = "Confirmed"
            action = "Confirmed"
        elif reject_clicked:
            selected_risk["review_status"] = "Rejected"
            action = "Rejected"

        log_change(ps, "risk", selected_risk["risk_id"], action, "record", old_record, selected_risk, "human", change_reason)
        save_state(ps)
        st.success(f"{selected_risk['risk_id']} 已保存")
        st.rerun()
