from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List

import streamlit as st

from core.data_model import PRIORITY_LEVELS, TestSuite, dataclass_to_dict
from core.llm_client import LlmClient, load_config
from core.risk_engine import build_risk_item
from core.state_manager import (
    find_requirement,
    find_risk_by_req_id,
    generate_risk_id,
    generate_suite_id,
    get_state,
    save_state,
)
from core.test_suite_manager import (
    SUITE_TECHNIQUE_LABELS,
    ensure_default_test_suites,
    infer_suite_techniques,
    sync_coverage_suite_ids,
    technique_internal_from_labels,
    technique_labels_from_internal,
)
from utils.change_tracker import log_change
from utils.ui import apply_reference_theme, render_hero, render_workflow_sidebar


def render_risk_matrix(risk_items: List[Dict[str, Any]]) -> str:
    matrix = {(impact, likelihood): [] for impact in range(1, 6) for likelihood in range(1, 6)}
    for item in risk_items:
        key = (int(item.get("impact", 1)), int(item.get("likelihood", 1)))
        matrix[key].append(item.get("req_id", ""))

    html = ['<table style="border-collapse:collapse;width:100%;font-size:13px;">']
    html.append("<tr><th style='padding:6px;border:1px solid #ddd;'>Impact \\ Likelihood</th>")
    for likelihood in range(1, 6):
        html.append(f"<th style='padding:6px;border:1px solid #ddd;'>{likelihood}</th>")
    html.append("</tr>")

    for impact in range(5, 0, -1):
        html.append(f"<tr><th style='padding:6px;border:1px solid #ddd;'>{impact}</th>")
        for likelihood in range(1, 6):
            score = impact * likelihood
            if score >= 12:
                bg = "#FECACA"
            elif score >= 6:
                bg = "#FEF3C7"
            else:
                bg = "#DCFCE7"
            reqs = "<br/>".join(matrix[(impact, likelihood)]) or "&nbsp;"
            html.append(
                f"<td style='vertical-align:top;padding:6px;border:1px solid #ddd;background:{bg};min-width:80px;'>{reqs}</td>"
            )
        html.append("</tr>")
    html.append("</table>")
    return "".join(html)


def generate_or_update_risk(ps: Dict[str, Any], requirement: Dict[str, Any], parsed_req: Dict[str, Any], use_llm: bool, llm_client: LlmClient) -> str:
    existing = find_risk_by_req_id(ps, requirement["req_id"])
    record = build_risk_item(
        requirement,
        parsed_req,
        risk_id=existing["risk_id"] if existing else generate_risk_id(ps),
        use_llm=use_llm,
        llm_client=llm_client,
        review_status="Draft",
        last_edited_by="llm",
    )
    if existing:
        old_record = deepcopy(existing)
        existing.update(record)
        log_change(ps, "risk", existing["risk_id"], "Regenerated", "record", old_record, existing, "llm", "Regenerated by risk page")
        return existing["risk_id"]

    ps["risk_items"].append(record)
    log_change(ps, "risk", record["risk_id"], "Created", "record", None, record, "llm", "Initial risk generation")
    return record["risk_id"]


def switch_page_safe(target: str, fallback_message: str) -> None:
    if hasattr(st, "switch_page"):
        st.switch_page(target)
    else:
        st.success(fallback_message)


def suite_priority_from_requirements(ps: Dict[str, Any], requirement_ids: List[str]) -> str:
    risk_map = {item.get("req_id"): item for item in ps.get("risk_items", [])}
    levels = [risk_map.get(req_id, {}).get("risk_level", "Medium") for req_id in requirement_ids]
    if "High" in levels:
        return "High"
    if "Medium" in levels:
        return "Medium"
    return "Low"


def delete_suite(ps: Dict[str, Any], suite_id: str) -> None:
    ps["test_suites"] = [item for item in ps.get("test_suites", []) if item.get("suite_id") != suite_id]
    for coverage_item in ps.get("coverage_items", []):
        coverage_item["suite_ids"] = [item for item in coverage_item.get("suite_ids", []) if item != suite_id]
    for test_case in ps.get("test_cases", []):
        test_case["suite_ids"] = [item for item in test_case.get("suite_ids", []) if item != suite_id]


st.set_page_config(page_title="Risk Assessment", layout="wide", page_icon=":triangular_flag_on_post:")
apply_reference_theme()

ps = get_state()
use_llm = bool(st.session_state.get("use_llm", False))
llm_client = LlmClient(load_config())

auto_changed = ensure_default_test_suites(ps)
auto_changed = sync_coverage_suite_ids(ps) or auto_changed
if auto_changed:
    save_state(ps)

with st.sidebar:
    render_workflow_sidebar("Risk Assessment")

render_hero(
    "Risk-Based Prioritization",
    "Risk Assessment",
    "Keep the risk view on the left, then shape suite-level test planning on the right before diving into coverage design.",
)

parsed_requirements = [item for item in ps["parsed_requirements"] if item.get("review_status") == "Approved"]
risk_items = ps["risk_items"]

eligible_requirements: List[tuple[int, Dict[str, Any], Dict[str, Any], Dict[str, Any] | None]] = []
for parsed_req in parsed_requirements:
    requirement = find_requirement(ps, parsed_req["req_id"])
    if requirement is None:
        continue
    risk_item = find_risk_by_req_id(ps, parsed_req["req_id"])
    eligible_requirements.append((int(risk_item.get("risk_score", 0)) if risk_item else 0, requirement, parsed_req, risk_item))
eligible_requirements.sort(key=lambda item: item[0], reverse=True)

left_col, right_col = st.columns([1.05, 0.95], gap="large")

with left_col:
    high_count = len([item for item in risk_items if item.get("risk_level") == "High"])
    medium_count = len([item for item in risk_items if item.get("risk_level") == "Medium"])
    low_count = len([item for item in risk_items if item.get("risk_level") == "Low"])

    stat1, stat2, stat3 = st.columns(3)
    with stat1:
        st.metric("High Risk", high_count)
    with stat2:
        st.metric("Medium Risk", medium_count)
    with stat3:
        st.metric("Low Risk", low_count)

    st.markdown("### Risk Heatmap")
    st.markdown(render_risk_matrix(risk_items), unsafe_allow_html=True)

    if st.button("Batch Generate All Risks", type="secondary", use_container_width=True):
        st.session_state["confirm_batch_risk"] = True

    if st.session_state.get("confirm_batch_risk"):
        st.warning("This will generate or refresh risk items for all approved structured requirements and skip already confirmed records.")
        if st.button("Confirm Batch Risk Generation", key="confirm_batch_risk_btn", type="secondary", use_container_width=True):
            generated = 0
            skipped = 0
            for _, requirement, parsed_req, risk_item in eligible_requirements:
                if risk_item and risk_item.get("review_status") == "Confirmed":
                    skipped += 1
                    continue
                generate_or_update_risk(ps, requirement, parsed_req, use_llm, llm_client)
                generated += 1
            save_state(ps)
            st.session_state["confirm_batch_risk"] = False
            st.success(f"Generated or updated {generated} risk items, skipped {skipped} confirmed items.")
            st.rerun()

    if not eligible_requirements:
        st.info("No approved structured requirements yet. Approve requirements first, then come back for risk and suite planning.")
        st.stop()

    labels = []
    label_map: Dict[str, tuple[Dict[str, Any], Dict[str, Any], Dict[str, Any] | None]] = {}
    for score, requirement, parsed_req, risk_item in eligible_requirements:
        level = risk_item.get("risk_level", "Draft") if risk_item else "Draft"
        label = f"{requirement['req_id']} - {requirement['title']} [{level} / {score}]"
        labels.append(label)
        label_map[label] = (requirement, parsed_req, risk_item)

    st.markdown("### Requirements (Sorted by Risk)")
    selected_label = st.selectbox("Requirement List", labels)
    selected_requirement, selected_parsed, selected_risk = label_map[selected_label]

    if st.button("Generate Risk for Current Requirement", use_container_width=True):
        generate_or_update_risk(ps, selected_requirement, selected_parsed, use_llm, llm_client)
        save_state(ps)
        st.success("Risk assessment generated.")
        st.rerun()

    if selected_risk is None:
        st.info("This requirement does not have a risk item yet. Generate one first.")
    else:
        st.markdown("### Risk Detail")
        st.caption(selected_parsed.get("summary") or selected_requirement.get("raw_text", ""))
        st.write(f"Title: {selected_risk.get('risk_title', '')}")
        st.write(f"Summary: {selected_risk.get('risk_summary', '')}")
        st.metric("Risk Score", int(selected_risk.get("risk_score", 0)), selected_risk.get("risk_level", "Medium"))
        with st.expander("Rationale", expanded=False):
            st.write(selected_risk.get("rationale", ""))

with right_col:
    st.markdown(
        """
        <style>
        .stMultiSelect [data-baseweb="tag"],
        .stMultiSelect [data-baseweb="tag"] > div,
        .stMultiSelect [data-baseweb="tag"] > span {
            background: #FFF5DA !important;
            color: #6a4b1a !important;
            border: 1px solid rgba(168, 102, 31, 0.18) !important;
        }
        .stMultiSelect [data-baseweb="tag"] span,
        .stMultiSelect [data-baseweb="tag"] svg {
            color: #6a4b1a !important;
            fill: #6a4b1a !important;
        }
        .stMultiSelect [data-baseweb="tag"] svg *,
        .stMultiSelect [data-baseweb="tag"] path {
            fill: #6a4b1a !important;
            stroke: #6a4b1a !important;
        }
        .stForm {
            background: rgba(255, 248, 220, 0.9);
            border: 1px solid rgba(168, 102, 31, 0.12);
            border-radius: 22px;
            padding: 0.85rem 0.85rem 0.35rem 0.85rem;
        }
        .stForm .stButton > button[kind="primary"],
        .stForm button[kind="primary"],
        .stForm button[type="submit"],
        [data-testid="stFormSubmitButton"] > button,
        [data-testid="stFormSubmitButton"] button {
            background: linear-gradient(180deg, #f7d58f 0%, #efc46f 100%) !important;
            color: #53381b !important;
            border: 1px solid rgba(168, 102, 31, 0.18) !important;
            box-shadow: none !important;
        }
        [data-testid="stFormSubmitButton"] > button:hover,
        [data-testid="stFormSubmitButton"] button:hover,
        .stForm button[kind="primary"]:hover,
        .stForm button[type="submit"]:hover {
            background: linear-gradient(180deg, #f5ce7d 0%, #e9bc5f 100%) !important;
            color: #452c13 !important;
        }
        .stButton > button {
            white-space: nowrap !important;
            font-size: 0.95rem !important;
            line-height: 1.1 !important;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )

    st.markdown("### High-level Test Suite Design")
    st.caption("Auto-suggested suites can be edited before coverage planning. The design here will drive later coverage and case views.")

    all_requirement_options = {
        f"{item['req_id']} - {item['title']}": item["req_id"]
        for item in ps.get("requirements", [])
    }

    sorted_suites = sorted(
        ps.get("test_suites", []),
        key=lambda item: (
            ["High", "Medium", "Low"].index(item.get("priority", "Medium")) if item.get("priority", "Medium") in PRIORITY_LEVELS else 1,
            item.get("suite_id", ""),
        ),
    )

    for suite in sorted_suites:
        requirement_labels = [req_id for req_id in suite.get("requirement_ids", [])]
        technique_labels = technique_labels_from_internal(suite.get("selected_techniques", []))

        with st.container(border=True):
            top1, top2, top3 = st.columns([2.0, 0.8, 0.8])
            with top1:
                st.markdown(f"**{suite['suite_id']}  {suite['name']}**")
                st.caption(f"[{suite.get('priority', 'Medium')}]")
            with top2:
                edit_clicked = st.button("编辑", key=f"edit_suite_{suite['suite_id']}", use_container_width=True)
            with top3:
                delete_clicked = st.button("删除", key=f"delete_suite_{suite['suite_id']}", use_container_width=True)

            st.write("关联需求：", " ".join(requirement_labels) or "None")
            st.write("预选技术：", ", ".join(technique_labels) or "None")

            if delete_clicked:
                delete_suite(ps, suite["suite_id"])
                log_change(ps, "test_suite", suite["suite_id"], "Deleted", "record", suite, None, "human", "Deleted from suite design")
                save_state(ps)
                st.rerun()

            if edit_clicked or st.session_state.get("editing_suite_id") == suite["suite_id"]:
                st.session_state["editing_suite_id"] = suite["suite_id"]
                with st.form(f"suite_form_{suite['suite_id']}"):
                    suite_name = st.text_input("套件名称", value=suite.get("name", ""))
                    priority = st.selectbox(
                        "优先级",
                        PRIORITY_LEVELS,
                        index=PRIORITY_LEVELS.index(suite.get("priority", "Medium")) if suite.get("priority", "Medium") in PRIORITY_LEVELS else 1,
                    )
                    selected_requirement_labels = st.multiselect(
                        "关联需求",
                        options=list(all_requirement_options.keys()),
                        default=[label for label, req_id in all_requirement_options.items() if req_id in suite.get("requirement_ids", [])],
                    )
                    selected_technique_labels = st.multiselect(
                        "预选技术",
                        options=SUITE_TECHNIQUE_LABELS,
                        default=technique_labels,
                    )
                    notes = st.text_area("备注", value=suite.get("notes", ""), height=90)
                    submitted = st.form_submit_button("保存", type="primary", use_container_width=True)

                if submitted:
                    old_value = deepcopy(suite)
                    suite["name"] = suite_name.strip() or suite["suite_id"]
                    suite["priority"] = priority
                    suite["requirement_ids"] = [all_requirement_options[label] for label in selected_requirement_labels]
                    suite["selected_techniques"] = technique_internal_from_labels(selected_technique_labels)
                    suite["notes"] = notes.strip()
                    suite["last_edited_by"] = "human"
                    log_change(ps, "test_suite", suite["suite_id"], "Edited", "record", old_value, suite, "human", "Edited suite design")
                    save_state(ps)
                    st.session_state["editing_suite_id"] = None
                    st.rerun()

    if st.button("+ 新增套件", type="secondary", use_container_width=True):
        st.session_state["editing_suite_id"] = "__new_suite__"

    if st.session_state.get("editing_suite_id") == "__new_suite__":
        suggested_requirements = [item["req_id"] for _, item, _, _ in eligible_requirements[:3]]
        with st.form("new_suite_form"):
            suite_name = st.text_input("套件名称", value="New Test Suite")
            priority = st.selectbox("优先级", PRIORITY_LEVELS, index=1)
            selected_requirement_labels = st.multiselect(
                "关联需求",
                options=list(all_requirement_options.keys()),
                default=[label for label, req_id in all_requirement_options.items() if req_id in suggested_requirements],
            )
            selected_technique_labels = st.multiselect(
                "预选技术",
                options=SUITE_TECHNIQUE_LABELS,
                default=infer_suite_techniques(ps, suggested_requirements),
            )
            notes = st.text_area("备注", height=90)
            submitted = st.form_submit_button("保存", type="primary", use_container_width=True)

        if submitted:
            requirement_ids = [all_requirement_options[label] for label in selected_requirement_labels]
            new_suite = dataclass_to_dict(
                TestSuite(
                    suite_id=generate_suite_id(ps),
                    name=suite_name.strip() or "New Test Suite",
                    priority=priority or suite_priority_from_requirements(ps, requirement_ids),
                    requirement_ids=requirement_ids,
                    selected_techniques=technique_internal_from_labels(selected_technique_labels),
                    notes=notes.strip(),
                    last_edited_by="human",
                )
            )
            ps["test_suites"].append(new_suite)
            log_change(ps, "test_suite", new_suite["suite_id"], "Created", "record", None, new_suite, "human", "Created new suite")
            save_state(ps)
            st.session_state["editing_suite_id"] = None
            st.rerun()

    if st.button("确认套件设计", type="primary", use_container_width=True):
        sync_coverage_suite_ids(ps)
        save_state(ps)
        st.session_state["active_suite_id"] = ps["test_suites"][0]["suite_id"] if ps.get("test_suites") else ""
        switch_page_safe("pages/4_Coverage_Planning.py", "套件设计已确认，请前往 Coverage & Strategy 页面继续。")
